name: Update Weather in README

on:
  schedule:
    - cron: "*/2 * * * *"  # 매일 오후 3시 (UTC 기준 6시) -> 2분 마다
  workflow_dispatch:  # 수동 실행 가능

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: OpenWeather API로 서울 날씨 업데이트
        run: |
          pip install requests python-dotenv
          python update_weather.py
        env:
          WEATHER: ${{ secrets.WEATHER }}

      - name: 변경 사항 커밋 및 푸시
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --exit-code || git commit -m "chore: 날씨 정보 자동 업데이트"
          git pull origin main --rebase
          git push

